version: 1.0.{build}
clone_folder: c:\projects\zyan
image: Visual Studio 2019

cache:
- C:\ProgramData\chocolatey\lib -> appveyor.yml
  
before_build:
- nuget restore source\Zyan.sln
- choco install opencover.portable
- choco install codecov

build:
  project: source\Zyan.sln
  parallel: true
  verbosity: minimal

before_test:
- where vstest.console
- where nunit-console.exe
- copy C:\projects\zyan\bin\net46\Zyan.Communication.dll "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\*.*"
- copy C:\projects\zyan\bin\UnitTests\Zyan.Tests.dll "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\*.*"
- copy C:\projects\zyan\bin\UnitTests\InterLinq.* "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\*.*"
- copy C:\projects\zyan\bin\UnitTests3\*.* C:\Tools\NUnit\bin\
- cd C:\projects\zyan\bin\UnitTests\
- InterLinq.UnitTests.Server.exe install
- InterLinq.UnitTests.Server.exe start

test_script:
- OpenCover.Console.exe -returntargetcode -register:administrator -target:"C:\projects\zyan\bin\UnitTests\IntegrationTest_DistributedEvents.exe" -filter:"+[Zyan*]*" -output:".\ZyanIntegrationTestCoverage.xml"
- OpenCover.Console.exe -returntargetcode -register:administrator -target:"vstest.console.exe" -targetargs:"/logger:Appveyor C:\projects\zyan\bin\UnitTests\Zyan.Tests.dll" -filter:"+[*]* -[MemoDb]*" -output:".\ZyanUnitTestCoverage.xml"
- OpenCover.Console.exe -returntargetcode -register:administrator -target:"vstest.console.exe" -targetargs:"/logger:Appveyor C:\projects\zyan\bin\UnitTests\InterLinq.UnitTests.dll" -output:".\InterLinqUnitTestCoverage.xml"
- nunit-console.exe C:\projects\zyan\bin\UnitTests3\Zyan.Tests.Fx3.dll /domain=None /noshadow 

after_test:
- codecov -f "ZyanIntegrationTestCoverage.xml"
- codecov -f "ZyanUnitTestCoverage.xml"
- codecov -f "InterLinqUnitTestCoverage.xml"
- C:\projects\zyan\bin\UnitTests\InterLinq.UnitTests.Server.exe stop
