version: 1.0.{build}
clone_folder: c:\projects\zyan
image: Visual Studio 2019

before_build:
- chcp 65001
- nuget restore source\Zyan.sln
- choco install opencover.portable
- choco install codecov
- C:\projects\zyan\tools\SnTools\sngen.bat C:\projects\zyan\source\

build:
  project: source\Zyan.sln
  parallel: true
  verbosity: minimal

before_test:
- where vstest.console
- where nunit3-console
#- copy C:\projects\zyan\bin\UnitTests\InterLinq.* "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\*.*"
- copy C:\projects\zyan\bin\UnitTests\Debug\net461\Zyan.Communication.dll "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\*.*"
- copy C:\projects\zyan\bin\UnitTests\Debug\net461\Zyan.Communication.dll "C:\Tools\NUnit3\bin\*.*"
#- copy C:\projects\zyan\bin\UnitTests\Debug\net46\Zyan.Tests.dll "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\*.*"
#- copy C:\projects\zyan\bin\UnitTests\Debug\net35\Zyan.* C:\Tools\NUnit3\
#- cd C:\projects\zyan\bin\UnitTests\
- C:\projects\zyan\bin\UnitTests\InterLinq.UnitTests.Server.exe install
- C:\projects\zyan\bin\UnitTests\InterLinq.UnitTests.Server.exe start

test_script:
- vstest.console.exe C:\projects\zyan\bin\UnitTests\Debug\net35\Zyan.Tests.dll /Framework:framework35
- OpenCover.Console.exe -returntargetcode -register:administrator -target:"C:\projects\zyan\bin\UnitTests\IntegrationTest_DistributedEvents.exe" -filter:"+[Zyan*]*" -output:".\ZyanIntegrationTestCoverage.xml"
- OpenCover.Console.exe -returntargetcode -register:administrator -target:"vstest.console.exe" -targetargs:"/logger:Appveyor C:\projects\zyan\bin\UnitTests\Debug\net461\Zyan.Tests.dll" -filter:"+[*]* -[MemoDb]*" -output:".\ZyanUnitTestCoverage.xml"
- OpenCover.Console.exe -returntargetcode -register:administrator -target:"vstest.console.exe" -targetargs:"/logger:Appveyor C:\projects\zyan\bin\UnitTests\InterLinq.UnitTests.dll" -output:".\InterLinqUnitTestCoverage.xml"

after_test:
- codecov -f "ZyanIntegrationTestCoverage.xml"
- codecov -f "ZyanUnitTestCoverage.xml"
- codecov -f "InterLinqUnitTestCoverage.xml"
- C:\projects\zyan\bin\UnitTests\InterLinq.UnitTests.Server.exe stop
